/* tslint:disable */
/* eslint-disable */
/**
 * Earthpoints API
 * Earthpoints API description
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateUserDto
 */
export interface CreateUserDto {
    /**
     * 
     * @type {string}
     * @memberof CreateUserDto
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUserDto
     */
    email?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateUserDto
     */
    emails?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CreateUserDto
     */
    timezone?: string;
    /**
     * 
     * @type {Date}
     * @memberof CreateUserDto
     */
    createdAt?: Date;
}

export function CreateUserDtoFromJSON(json: any): CreateUserDto {
    return CreateUserDtoFromJSONTyped(json, false);
}

export function CreateUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'firstName': !exists(json, 'firstName') ? undefined : json['firstName'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'emails': !exists(json, 'emails') ? undefined : json['emails'],
        'timezone': !exists(json, 'timezone') ? undefined : json['timezone'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
    };
}

export function CreateUserDtoToJSON(value?: CreateUserDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'firstName': value.firstName,
        'email': value.email,
        'emails': value.emails,
        'timezone': value.timezone,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
    };
}

