/* tslint:disable */
/* eslint-disable */
/**
 * Earthpoints API
 * Earthpoints API description
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UserFromExternalPlatformDataDto,
    UserFromExternalPlatformDataDtoFromJSON,
    UserFromExternalPlatformDataDtoFromJSONTyped,
    UserFromExternalPlatformDataDtoToJSON,
} from './UserFromExternalPlatformDataDto';

/**
 * 
 * @export
 * @interface CreatePointEventDto
 */
export interface CreatePointEventDto {
    /**
     * The hash string is used to make sure each event will only result in points awarded once. It should be unique for each event and user, in such a way the same hashString will predictably get generated if the same event was sent again. For example, it could be the string "created-pledge-page" followed by the user's id in another system.
     * @type {string}
     * @memberof CreatePointEventDto
     */
    hashString: string;
    /**
     * Already existing User UUID in the system. One of this or an email is required.
     * @type {string}
     * @memberof CreatePointEventDto
     */
    userid?: string;
    /**
     * External platform user data. This is used to identify the correct user. If no user is found, a new user will be created and tagged with the provided external credentials.
     * @type {Array<UserFromExternalPlatformDataDto>}
     * @memberof CreatePointEventDto
     */
    externalPlatformUserData?: Array<UserFromExternalPlatformDataDto>;
    /**
     * Email to associate the points with. If an user with this email is not found, a new user will be created. One of this or an User UUID is required.
     * @type {string}
     * @memberof CreatePointEventDto
     */
    email?: string;
    /**
     * Icon to display in web interface (Font Awesome version 6.0.0)
     * @type {string}
     * @memberof CreatePointEventDto
     */
    icon?: string;
    /**
     * The verb to display along with the point event in user interfaces. For example: "You connected Facebook"
     * @type {string}
     * @memberof CreatePointEventDto
     */
    verb: string;
    /**
     * Social platform (twitter, instagram, facebook) or other external platform where the event was awarded from
     * @type {string}
     * @memberof CreatePointEventDto
     */
    platform: string;
    /**
     * Message to display to the user.
     * @type {string}
     * @memberof CreatePointEventDto
     */
    message: string;
    /**
     * For awarding points, set this to false. Set to true if you want to consume points instead of awarding them
     * @type {boolean}
     * @memberof CreatePointEventDto
     */
    isBurn: boolean;
    /**
     * Number of points to award for this event.
     * @type {number}
     * @memberof CreatePointEventDto
     */
    points: number;
    /**
     * For displaying to the user, the related time when the points were awarded.
     * @type {Date}
     * @memberof CreatePointEventDto
     */
    timestamp: Date;
    /**
     * Any custom metadata
     * @type {object}
     * @memberof CreatePointEventDto
     */
    metadata: object;
}

export function CreatePointEventDtoFromJSON(json: any): CreatePointEventDto {
    return CreatePointEventDtoFromJSONTyped(json, false);
}

export function CreatePointEventDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePointEventDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hashString': json['hashString'],
        'userid': !exists(json, 'userid') ? undefined : json['userid'],
        'externalPlatformUserData': !exists(json, 'externalPlatformUserData') ? undefined : ((json['externalPlatformUserData'] as Array<any>).map(UserFromExternalPlatformDataDtoFromJSON)),
        'email': !exists(json, 'email') ? undefined : json['email'],
        'icon': !exists(json, 'icon') ? undefined : json['icon'],
        'verb': json['verb'],
        'platform': json['platform'],
        'message': json['message'],
        'isBurn': json['isBurn'],
        'points': json['points'],
        'timestamp': (new Date(json['timestamp'])),
        'metadata': json['metadata'],
    };
}

export function CreatePointEventDtoToJSON(value?: CreatePointEventDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hashString': value.hashString,
        'userid': value.userid,
        'externalPlatformUserData': value.externalPlatformUserData === undefined ? undefined : ((value.externalPlatformUserData as Array<any>).map(UserFromExternalPlatformDataDtoToJSON)),
        'email': value.email,
        'icon': value.icon,
        'verb': value.verb,
        'platform': value.platform,
        'message': value.message,
        'isBurn': value.isBurn,
        'points': value.points,
        'timestamp': (value.timestamp.toISOString()),
        'metadata': value.metadata,
    };
}

