/* tslint:disable */
/* eslint-disable */
/**
 * Earthpoints API
 * Earthpoints API description
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PointEvent,
    PointEventFromJSON,
    PointEventFromJSONTyped,
    PointEventToJSON,
} from './PointEvent';

/**
 * 
 * @export
 * @interface CreatePointEventResponseDto
 */
export interface CreatePointEventResponseDto {
    /**
     * 
     * @type {string}
     * @memberof CreatePointEventResponseDto
     */
    msg: string;
    /**
     * 
     * @type {PointEvent}
     * @memberof CreatePointEventResponseDto
     */
    event: PointEvent;
    /**
     * 
     * @type {number}
     * @memberof CreatePointEventResponseDto
     */
    userTotalPoints: number;
}

export function CreatePointEventResponseDtoFromJSON(json: any): CreatePointEventResponseDto {
    return CreatePointEventResponseDtoFromJSONTyped(json, false);
}

export function CreatePointEventResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePointEventResponseDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'msg': json['msg'],
        'event': PointEventFromJSON(json['event']),
        'userTotalPoints': json['userTotalPoints'],
    };
}

export function CreatePointEventResponseDtoToJSON(value?: CreatePointEventResponseDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'msg': value.msg,
        'event': PointEventToJSON(value.event),
        'userTotalPoints': value.userTotalPoints,
    };
}

