/* tslint:disable */
/* eslint-disable */
/**
 * Earthpoints API
 * Earthpoints API description
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserFromExternalPlatformDataDto
 */
export interface UserFromExternalPlatformDataDto {
    /**
     * 
     * @type {string}
     * @memberof UserFromExternalPlatformDataDto
     */
    profileId: string;
    /**
     * 
     * @type {string}
     * @memberof UserFromExternalPlatformDataDto
     */
    platform: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserFromExternalPlatformDataDto
     */
    emails?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof UserFromExternalPlatformDataDto
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof UserFromExternalPlatformDataDto
     */
    phone?: number;
    /**
     * 
     * @type {string}
     * @memberof UserFromExternalPlatformDataDto
     */
    authToken?: string;
    /**
     * 
     * @type {string}
     * @memberof UserFromExternalPlatformDataDto
     */
    tokenSecret?: string;
    /**
     * 
     * @type {Date}
     * @memberof UserFromExternalPlatformDataDto
     */
    authExpiration?: Date;
}

export function UserFromExternalPlatformDataDtoFromJSON(json: any): UserFromExternalPlatformDataDto {
    return UserFromExternalPlatformDataDtoFromJSONTyped(json, false);
}

export function UserFromExternalPlatformDataDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserFromExternalPlatformDataDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'profileId': json['profile_id'],
        'platform': json['platform'],
        'emails': !exists(json, 'emails') ? undefined : json['emails'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
        'authToken': !exists(json, 'auth_token') ? undefined : json['auth_token'],
        'tokenSecret': !exists(json, 'token_secret') ? undefined : json['token_secret'],
        'authExpiration': !exists(json, 'auth_expiration') ? undefined : (new Date(json['auth_expiration'])),
    };
}

export function UserFromExternalPlatformDataDtoToJSON(value?: UserFromExternalPlatformDataDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'profile_id': value.profileId,
        'platform': value.platform,
        'emails': value.emails,
        'name': value.name,
        'phone': value.phone,
        'auth_token': value.authToken,
        'token_secret': value.tokenSecret,
        'auth_expiration': value.authExpiration === undefined ? undefined : (value.authExpiration.toISOString()),
    };
}

