/* tslint:disable */
/* eslint-disable */
/**
 * Earthpoints API
 * Earthpoints API description
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {string}
     * @memberof User
     */
    userid: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    email: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof User
     */
    emails: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    timezone: string;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    createdAt: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof User
     */
    events: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof User
     */
    connections: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    points: number;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    lastEmailed: Date;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userid': json['userid'],
        'firstName': json['firstName'],
        'email': json['email'],
        'emails': json['emails'],
        'timezone': json['timezone'],
        'createdAt': (new Date(json['createdAt'])),
        'events': json['events'],
        'connections': json['connections'],
        'points': json['points'],
        'lastEmailed': (new Date(json['lastEmailed'])),
    };
}

export function UserToJSON(value?: User | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userid': value.userid,
        'firstName': value.firstName,
        'email': value.email,
        'emails': value.emails,
        'timezone': value.timezone,
        'createdAt': (value.createdAt.toISOString()),
        'events': value.events,
        'connections': value.connections,
        'points': value.points,
        'lastEmailed': (value.lastEmailed.toISOString()),
    };
}

